<Project>
  <PropertyGroup>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);NU1901;NU1902;NU1903;NU1904;NU1905;CS8600;CS8601;CS8602;CS8603;CS8604;CS8618;CS8619;CS8625;CS8765;CS8608;SYSLIB0050;CS0618;CS1998;CS0436;CS1591;CS0114;CS0472;CS0105;CS8981;CS0168;CA2200</NoWarn>
  </PropertyGroup>
</Project>
